### PR TITLE
Clarification on model ACEc and ACE

### PR DESCRIPTION
**Pull request by jinningwang**
https://github.com/CURENT/andes/issues/585

- Fix ACEc.bias.tex_name
- Change ACEc.bias.default to -1 to follow NERC's definition
- Add references

### CODE REVIEW

**Comment by jinningwang** [comment]
@cuihantao 
One question regarding this PR.

As here I changed the default value and equation, it seems to be a potential breaking change. Before manually updating parameters of ``ACEc.bias``, users can run into unexpected results.

So, I'd like your suggesstion that which option would be better for us?
1. Revise the equations: use ``abs()`` to eliminate the impact of sign
2. If there is a parameter correction step, correct positive values to negative

**Comment by cuihantao** [comment]
If it's always going to be a negative value, you can use "abs". This is to safeguard users who entered the value mistakenly as a positive value. 

If both positive and negative values have a meaning, then we should do any correction to parameter but rather correct the equation.

**Comment by jinningwang** [comment]
> Bias and frequency response are both expressed as negative numbers. In other words, as frequency drops, MW output (β) or desired output (B) increases. Both are measured in MW/0.1 Hz

Given NERC's suggestion, I update the PR with first option.

**Comment by jinningwang** [comment]
@cuihantao ready to merge

**Comment by cuihantao** [comment]
Jinning, thanks!! I'll tag a new version shortly.

**Pull request merged**
