### PR TITLE
Update doc to promote CURENT

### PR DESCRIPTION
**Pull request by jinningwang**
Update CURENT logo in README and home page of documentation
Update links
Remove dependencies of GridCal

### CODE REVIEW

**Comment by jinningwang** [comment]
Two errors I haven't figured out yet.
1. Making documentation, ``[autosummary] failed to import andes.io.em_psse.get_signals.``, but there is not such a module.
2. The CI failed because of codecov, not sure what's the reason.
```
ERROR: Could not find a version that satisfies the requirement codecov (from andes[all]) (from versions: none)
ERROR: No matching distribution found for codecov
Error: Process completed with exit code 1.
```

**Comment by cuihantao** [comment]
Thanks, Jinning.

For 2, you can check if `codecov` is still installable. There has been some changes with the company. Doing a search might point you to some news. You might consider disabling it for now and using another coverage service in the future.

For 1, I removed `em_psse` and probably forgot to remove some references to it in autodocs. You can use global search to find and remove them, and see if it fixes it.

**Comment by cuihantao** [comment]
Please also double check the README preview. I skimed through it and saw `<br>`

**Comment by jinningwang** [comment]
I have removed the ``codecov  # Upload the report to codecov.`` on Linux, but there is another error when running CI that I don't have access to check and fix.

The error message:
```
Publishing test results to test run '17702'.
TestResults To Publish 67, Test run id:17702
Test results publishing 67, remaining: 0. Test run id: 17702
No source for code: '/home/vsts/work/1/s/(builtin)'.
##[error]Bash exited with code '1'.
```

**Comment by cuihantao** [comment]
The CURENT logo in the README is of very low resolution. Need to replace it with a high-quality PNG or SVG image, preferably with a transparent background. 

The CI error is probably due to changes in GridCal. Some options to consider:

- Fix the version of GridCal that we depend on
- Remove dependency on GridCal; update the interop module to let the users install GridCal manually if they need it. We will lose the ability to test the interface then.

**Comment by jinningwang** [comment]
After a brief test, I choose to remove GridCal from dependencies for now. The installation of GridCal is buggy with PySide2.
it can be added later on if the contributor of the interface with GridCal can address this dependency issue.

> The CURENT logo in the README is of very low resolution. Need to replace it with a high-quality PNG or SVG image, preferably with a transparent background.
> 
> The CI error is probably due to changes in GridCal. Some options to consider:
> 
> * Fix the version of GridCal that we depend on
> * Remove dependency on GridCal; update the interop module to let the users install GridCal manually if they need it. We will lose the ability to test the interface then.

**Comment by cuihantao** [comment]
Can you resize the CURENT logo...

**Pull request merged**
